# VISPAD INSTITUTE OF TECHNOLOGY
## DATABLOOM LAB ASSIGNMENT 1

**Instructions:**  
- Work individually or in pairs. Show your work where arithmetic is required.  
- Submit this notebook with your answers (code outputs + short written answers).
- You may use **NumPy OR pure Python** — **any method is allowed**.
- Total: **20 points**. Deadlines: *TUESDAY, 28TH OCTOBER, 2025*.


**1. Given:**  
$$
\mathbf{u} = \begin{bmatrix} 2 \\ 3 \end{bmatrix}, \quad
\mathbf{v} = \begin{bmatrix} 4 \\ -1 \end{bmatrix}
$$

**Write code to compute:**  
$$
\mathbf{u} + \mathbf{v}
$$

In [1]:
import numpy as np

In [2]:
u = np.array([2, 3])
v = np.array([4, -1])

u+v

array([6, 2])

u + v is a vector addition. (Element-wise addition)

**2. Given:**  
$$
\mathbf{w} = \begin{bmatrix} 3 \\ -2 \end{bmatrix}, \quad
\text{scalar} = 4
$$

**Write code to compute:**  
$$
4 \times \mathbf{w}
$$

In [3]:
w = np.array([3, -2])
4*w

array([12, -8])

4 x **w** is a scaler multiplication operation (vector **w** is scaled by 4)

**3. Let:**  
$$
\mathbf{a} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \quad
\mathbf{b} = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}
$$

**Write code to compute:**  
$$
2\mathbf{a} + 3\mathbf{b}
$$

*(Scalar multiply both first, then add)*

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

2*a + 3*b

array([14, 19, 24])

This is a combination of scaler multiplication and vector addition. (A linear combination of **a** and **b**).

**4. Write a Python function:**

```python
def add_vectors(v1, v2):

```

Test it with:

v1 = [5, 0, 2] <br>
v2 = [1, 1, 1]
    

In [5]:
def add_vectors(v1, v2):
    if len(v1) != len(v2):
        print("vector addition requires vectors to be of equal size")
    output = []
    for v_i, v_j in zip(v1, v2):
        output.append(v_i + v_j)
    return output

In [6]:
v1 = [5, 0, 2]
v2 = [1, 1, 1]

add_vectors(v1, v2)

[6, 1, 3]

**5.** Using **NumPy**, show that

$$
\mathbf{v}_1 = \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad
\mathbf{v}_2 = \begin{bmatrix} 2 \\ 4 \end{bmatrix}
$$

are **linearly dependent** by finding **non-zero** scalars \(c1, c2\) such that

$$
c_1 \mathbf{v}_1 + c_2 \mathbf{v}_2 = \mathbf{0}.
$$

In [7]:
v1 = np.array([1, 2])
v2 = np.array([2, 4])

-2*v1 + 1*v2

array([0, 0])

$$
c_1 \mathbf{v}_1 + c_2 \mathbf{v}_2 = \mathbf{0}.
$$

where:

$$ c_1 = -2 $$ and $$ c_2 = 1 $$

**6.** Using **NumPy**, show that

$$
\mathbf{v}_1 = \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad
\mathbf{v}_2 = \begin{bmatrix} 3 \\ 1 \end{bmatrix}
$$

are **linearly independent** by attempting to find **non-trivial** scalars and **explaining the result**.

In [8]:
v1 = np.array([1, 2])
v2 = np.array([3, 1])


def check_dependency(v1, v2):
    coef = [c for c in np.arange(-9.0, 10, 0.1) if c != 0]
    for c1 in coef:
        for c2 in coef:
            vector_sum = c1*v1 + c2*v2 
            if np.array_equal(vector_sum, np.zeros(v1.shape)):
                print(f"Linear dependency detected with c1 = {c1} and c2 = {c2}")
    print(f"{v1} and {v2} are linearly independent")

check_dependency(v1, v2)

[1 2] and [3 1] are linearly independent


The function above checks all possible linear combinations of **v1** and **v2** between -9.0 and +9.9 with a step value of 0.1, and if any one of the combinations results in a zero vector it prints out the values of the coefficients, otherwise, it displays that the two vectors are linearly independent.

while not an exhaustive search, since the range of real numbers is infinite, the function limits itself to the specified range of values. 

**7. You are given the following two vectors:**

$$
\mathbf{u} = \begin{bmatrix} 2 \\ 1 \end{bmatrix}, \quad
\mathbf{v} = \begin{bmatrix} 1 \\ 3 \end{bmatrix}
$$

What does it mean to say that **“u and v span ℝ²”**?  
Explain in **simple words**, in **not more than 3 sentences**.

**u** and **v** span **ℝ²** if every vector in **ℝ²** can be written as a linear combination (scalar multiplication and vector addition) of **u** and **v**.

**8. Write Python code to check whether the vector**

$$
\mathbf{w} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}
$$

can be **expressed as a linear combination** of **u** and **v**.

In other words — find **scalars** \(a\) and \(b\) such that:

$$
a\mathbf{u} + b\mathbf{v} = \mathbf{w}
$$

In [9]:
u = np.array([2, 1])
v = np.array([1, 3])
w = np.array([5, 7])

matrix = []

for a_i, b_i in zip(u, v):
    matrix.append([a_i, b_i])
    
matrix_a = np.array(matrix)
matrix_a_inv = np.linalg.inv(matrix_a)
answer_vector = matrix_a_inv@w

print(f"The scalers a and b are {answer_vector}\n")
print(f"A = ([u, v]) = \n {matrix_a}\n")
print(f"a, b = \n {answer_vector.reshape(2, 1)}\n")
print(f"A x [a, b] = \n {(matrix_a @ answer_vector).reshape(2, 1)}")

The scalers a and b are [1.6 1.8]

A = ([u, v]) = 
 [[2 1]
 [1 3]]

a, b = 
 [[1.6]
 [1.8]]

A x [a, b] = 
 [[5.]
 [7.]]


**9. Given the new basis**
$$
\mathbf{w} = \begin{bmatrix} 1 \\[4pt] 1 \end{bmatrix}, \qquad
\mathbf{z} = \begin{bmatrix} 1 \\[4pt] -1 \end{bmatrix},
$$

**(a)** Find coordinates \(\begin{bmatrix} c_1 \\ c_2 \end{bmatrix}\) such that
$$
\begin{bmatrix} 3 \\[4pt] 2 \end{bmatrix}
= c_1 \mathbf{w} + c_2 \mathbf{z}.
$$


**(b)** Provide a short plain-English sentence explaining what *changing basis* means in machine learning.  
**(c)** Compute the coordinates of the vector

$$
\mathbf{h} = \begin{bmatrix} 4 \\[4pt] 5 \end{bmatrix}
$$

in the new basis

$$
\{ \mathbf{w}, \mathbf{z} \}.
$$

That is, find

$$
\mathbf{h}^*.
$$


In [10]:
def find_coef(u, v, w):
    matrix = []

    for a_i, b_i in zip(u, v):
        matrix.append([a_i, b_i])
    
    matrix_a = np.array(matrix)
    matrix_a_inv = np.linalg.inv(matrix_a)
    answer_vector = matrix_a_inv@w
    return answer_vector

In [11]:
w = np.array([1, 1])
z = np.array([1, -1])
b = np.array([3, 2])

c1, c2 = find_coef(w, z, b)
print(f"c1 = {c1}\nc2 = {c2}")

c1 = 2.5
c2 = 0.5


changing basis simply means changing coordinate system (in whatever dimension we may be working in)

In [12]:
h = np.array([4, 5])

h_coord = find_coef(w, z, h)
c1, c2 = h_coord
print(f"c1 = {c1}\nc2 = {c2}")
print(f"h* = {h_coord}")

c1 = 4.5
c2 = -0.5
h* = [ 4.5 -0.5]


**10. (a)** How many basis vectors are needed to represent data in $\mathbb{R}^5\$?  
**(b)** Give a short machine learning example (1–2 lines) where reducing dimension (feature selection or transformation) could help improve a model.  

a. 5


b. A dataset with 30 numerical features for predicting a customer's purchase, where 20 features are mostly random noise, can be improved by selecting the 10 most informative features, leading to a more accurate model and lower computational and cost.

## DataBloom — where data comes alive! ☺