# VISPAD INSTITUTE OF TECHNOLOGY 



<div align="center">
  <img src="https://fe5lpvispw.ufs.sh/f/DFYBeUqk6Uo0WMFh1daytRZp0UOYH5KfDmivgEeALPsNBawJ" alt="Vispad lab image" width="700" />
</div>

## LAB ASSIGNMENT 3

**Instructions:**  
- Submit this notebook with your answers 
- Total: **20 points**. Deadlines: *Saturday, 8TH NOVEMBER, 2025*.


### SECTION 1: ORTHOGONAL PROJECTION (5 Points)


Given the two 3D vectors, $\mathbf{v} = [1, 2, 3]$ and $\mathbf{y} = [2, 0, 2]$:


a. Compute the orthogonal projection of $\mathbf{v}$ onto $\mathbf{y}$ (i.e., $proj_{\mathbf{y}}(\mathbf{v})$).


b. Compute the orthogonal component $\mathbf{v}_{\perp}$ (the part of $\mathbf{v}$ that is perpendicular to $\mathbf{y}$).


c. Verify that your $\mathbf{v}_{\perp}$ from part (b) is truly orthogonal to $\mathbf{y}$ by computing their dot product.



In [1]:
import numpy as np

def orthogonal_projection(a, b):
    """projection of a on b"""
    b_squared_norm = np.dot(b, b)
    
    if b_squared_norm == 0:
        return np.zeros_like(b)
        
    a_dot_b = np.dot(a, b)
    coef = a_dot_b / b_squared_norm
    return coef*b

def orthogonal_component(a, b):
    """Orthogonal component of a with respect to b"""
    return a - orthogonal_projection(a, b)

In [2]:
# a
v = np.array([1, 2, 3])
y = np.array([2, 0, 2])

v_proj_y = orthogonal_projection(v, y)
v_proj_y

array([2., 0., 2.])

In [3]:
# b

v_perp_y = orthogonal_component(v, y)
v_perp_y

array([-1.,  2.,  1.])

In [4]:
# c

if np.dot(y, v_perp_y) == 0:
    print("Orthogonality = True")
else:
    print("Orthogonality = False")

Orthogonality = True


### SECTION 2: CALCULATING ANGLE (5 Points)

Given the two 3D vectors, $\mathbf{a} = [3, 4, 0]$ and $\mathbf{b} = [0, 0, -5]$:


a. Compute the angle (in degrees) between $\mathbf{a}$ and $\mathbf{b}$.


b. Now, compute the angle (in degrees) between $\mathbf{a} = [3, 4, 0]$ and $\mathbf{c} = [3, 4, 5]$.


In [5]:
import math

def angles(a, b, unit='rad'):
    """Angle between a and b"""
    norm_a, norm_b = np.linalg.norm(a, 2), np.linalg.norm(b, 2)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    a_dot_b = np.dot(a, b)
    a_mul_b = norm_a * norm_b
    rad_ang = math.acos(np.clip(a_dot_b/a_mul_b, -1.0, 1.0))
    if unit=='rad':
        return rad_ang
    elif unit=='deg':
        return rad_ang*(180/math.pi)
    else:
        raise ValueError("Unit must be 'rad' or 'deg'")
        

In [6]:
# a

a = np.array([3, 4, 0])
b = np.array([0, 0, -5])

angle = angles(a, b, unit='deg')
(f'{angle:.2f} degrees')

'90.00 degrees'

In [7]:
# b

a = np.array([3, 4, 0])
b = np.array([3, 4, 5])

angle = angles(a, b, 'deg')
(f'{angle:.2f} degrees')

'45.00 degrees'

### SECTION 3: GRAM-SCHMIDT PROCESS (5 Points)

Given these vectors:

$\mathbf{v_1} = [2, 0, 0, 0]$

$\mathbf{v_2} = [1, 3, 0, 0]$

$\mathbf{v_3} = [1, 1, 4, 0]$

$\mathbf{v_4} = [2, 2, 1, 5]$

a. Apply the Gram-Schmidt process to find the orthogonal basis ${\mathbf{e_1}, \mathbf{e_2}, \mathbf{e_3}, \mathbf{e_4}}$. Print each of these new vectors.

b. Create the orthonormal basis ${\mathbf{u_1}, \mathbf{u_2}, \mathbf{u_3}, \mathbf{u_4}}$ by normalizing your orthogonal vectors from part (a). Print each of these unit vectors.


In [8]:
def orthogonal_bases(*args):
    """Implementation of the Gram-Schmidt process in generating orthogonal bases"""
    vectors = np.array(args, dtype=float)
    bases = [vectors[0].copy()]

    for v in vectors[1:]:
        v_orthogonal = v.copy()
        for u in bases:
            projection = orthogonal_projection(v, u)
            v_orthogonal -= projection
        if np.allclose(np.array(v_orthogonal), np.zeros_like(v_orthogonal)):
            continue
        bases.append(v_orthogonal)
    return np.array(bases)


def orthonormal_bases(*args):
    """Implementation of the Gram-Schmidt process in generating orthonormal bases"""
    ortho_bases = orthogonal_bases(*args)
    normalized_bases = []
    for base in ortho_bases:
        base_norm = np.linalg.norm(base)
        normalized_bases.append(base / base_norm)
    return np.array(normalized_bases)

In [9]:
# a

v1 = np.array([2, 0, 0, 0])
v2 = np.array([1, 3, 0, 0])
v3 = np.array([1, 1, 4, 0])
v4 = np.array([2, 2, 1, 5])


o_bases = orthogonal_bases(v1, v2, v3, v4)
print("Orthogonal Bases:")
print(o_bases)

Orthogonal Bases:
[[2. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 5.]]


In [10]:
# b

o_n_bases = orthonormal_bases(v1, v2, v3, v4)
print("Orthonormnal Bases:")
print(o_n_bases)

Orthonormnal Bases:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### SECTION 4: APPLICATION: DOCUMENT SIMILARITY (5 Points)

A simple "related article" finder works by counting keywords and using cosine similarity. We have a base_document and want to find which of two other articles is more similar to it.
The keyword counts are (in order): ['linear', 'algebra', 'vector', 'calculus']

base_doc = [5, 3, 2, 0]

article_A = [10, 5, 4, 1]

article_B = [0, 1, 5, 10]

a. Compute the Cosine Similarity between base_doc and article_A.


b. Compute the Cosine Similarity between base_doc and article_B.


c. In the markdown cell below, state which article you would recommend as "more similar" and explain why, based on your scores and the keyword counts.


In [11]:
# Answer goes here 
base_doc = np.array([5, 3, 2, 0])
article_A = np.array([10, 5, 4, 1])
article_B = np.array([0, 1, 5, 10])

# a
doc_to_A = angles(base_doc, article_A, 'rad')

# b
doc_to_B = angles(base_doc, article_B, 'rad')

print('The Cosine Similarity between: ')
print(f'Base Document and Article A is: {math.cos(doc_to_A):.3f}')
print(f'Base Document and Article B is: {math.cos(doc_to_B):.3f}')

The Cosine Similarity between: 
Base Document and Article A is: 0.994
Base Document and Article B is: 0.188


**# c**

Article A has a larger value for the Cosine Similarity than Article B.

This means that Article A is more similar to base_document than Article B.

This reasonable if we consider the word count, which shows that:
1. The base document dossn't contain the word 'calculus' but it is the most common word in Article B.
2. The most common word in the base document is also the most common word in Article A, which doesn't appear at all in Article B.
3. The proportions in the occurence of each word in the base document is rougly similar with that in Article A 